#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  1 23:45:51 2018

@author: rabnawaz
"""

# Iterative version
def triangleiter(n):
    result = 0
    for x in range(n+1):
        result = result + x
    return result

# Recursive version
def trianglerec(n):
    pass